{% set version = "1.23.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.oo
  version: {{ version|replace("-", "_") }}

source:
  fn: R.oo_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/R.oo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.oo/R.oo_{{ version }}.tar.gz
  sha256: f5124ce3dbb0a62e8ef1bfce2de2d1dc2f776e8c48fd8cac358f7f5feb592ea1

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r.methodss3 >=1.7.1
  run:
    - r-base
    - r-r.methodss3 >=1.7.1

test:
  commands:
    - $R -e "library('R.oo')"           # [not win]
    - "\"%R%\" -e \"library('R.oo')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/R.oo
  license: LGPL (>= 2.1)
  summary: Methods and classes for object-oriented programming in R with or without references.  Large
    effort has been made on making definition of methods as simple as possible with
    a minimum of maintenance for package developers.  The package has been developed
    since 2001 and is now considered very stable.  This is a cross-platform package
    implemented in pure R that defines standard S3 classes without any tricks.
  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1'

extra:
  recipe-maintainers:
    - conda-forge/r
