{% set version = "1.25.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.oo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R.oo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.oo/R.oo_{{ version }}.tar.gz
  sha256: b8b19061774918ee7d9d4330c16c0ea505f7cd02d01343df1e8b2e4fb847beef

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r.methodss3 >=1.7.1
  run:
    - r-base
    - r-r.methodss3 >=1.7.1

test:
  commands:
    - $R -e "library('R.oo')"           # [not win]
    - "\"%R%\" -e \"library('R.oo')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/R.oo
  license: LGPL-2.1-or-later
  summary: Methods and classes for object-oriented programming in R with or without references.  Large effort has been made on making definition of methods as simple as possible with a minimum of maintenance for package developers.  The package has been developed since 2001 and is now considered very stable.  This is a cross-platform
    package implemented in pure R that defines standard S3 classes without any tricks.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r
