appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CBfcurNSCtg4OP7k/TalUe5wGg33Kha3I8JB67OvTWSidaw2HwbTSop+4kJdRuY1QaeaoQpW2jlMsCzg7fXjUnwAcEZW3yU6sHkoz7ekx0T+aPmsdwtc6lxSvT5D9i4Bx2hJSeUIFCrmg9P1EXUwzgCHZUcWNSie3s7CYqdAZiUE1jZtpDd0bl0ZfzkDKmty6d3efCZe7BkuzJEYnXgkf9eqRR6pW+zlWUEWlTBo2tNCUbARJXvjh26d2nDtz0E3uWz0ieCU4uGKFrPqduNk/kqg4mVp/AlTM1nA53I7iroFVNsrriQzMEKN5lwjKJDU2Eidc1iEUMCFI/x4s6FIRhm/7iVSzHjIif+hw0NrX8KpqObUm/PQZt21N13V6oEP37JoQC23rvaiAnMUJf1mC0PA7HuqDCoSvggK4QV/7moQSvDJovTAjiaR+Ssgul8KZ97rNMCtkVSoIvkXzdFlCDxBaeFzgU+t9ZyUkNcw7H/TW1VMZacpZzrGRp6wutPdQqLmnFIioCdeiSSwk5RWV05rRFZFj3UsQUdwM1AxHc6s/Bj6ii4L1O2mNEjbXteQH5lbPaKRi7p1hX4Ua9jsjjwM7itLsRH0581j9bqQ9mA3vOo+qztvYXAG4A5zoQKxtG1ieohHHL6RWDLWbHSXZx7orRfyLMdT+foNLzPVwH0=}
